# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\nhelloworld\"\x1e\n\x0eMessageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cMessageReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa1\x01\n\nChatServer\x12\x42\n\x08SayHello\x12\x1a.helloworld.MessageRequest\x1a\x18.helloworld.MessageReply\"\x00\x12O\n\x13SayHelloStreamReply\x12\x1a.helloworld.MessageRequest\x1a\x18.helloworld.MessageReply\"\x00\x30\x01\x42\x36\n\x1aio.grpc.modules.chatserverB\x0f\x43hatServerProtoP\x01\xa2\x02\x04\x43HSRb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032io.grpc.modules.chatserverB\017ChatServerProtoP\001\242\002\004CHSR'
  _MESSAGEREQUEST._serialized_start=26
  _MESSAGEREQUEST._serialized_end=56
  _MESSAGEREPLY._serialized_start=58
  _MESSAGEREPLY._serialized_end=89
  _CHATSERVER._serialized_start=92
  _CHATSERVER._serialized_end=253
# @@protoc_insertion_point(module_scope)
